#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI9882N)	+= touch_ili9882n.o
obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI9882N)	+= touch_ili9882n_fw.o
obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI9882N)	+= touch_ili9882n_mp.o
obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI9882N)	+= touch_ili9882n_apk.o
