#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_LGSIW_SW49110)	+= touch_sw49110.o
obj-$(CONFIG_LGE_TOUCH_LGSIW_SW49110)	+= touch_sw49110_prd.o
