
subdir-ccflags-$(CONFIG_LGE_TOUCH_CORE) += -I$(srctree)/drivers/input/touchscreen/lge
subdir-ccflags-$(CONFIG_LGE_TOUCH_CORE_OOS) += -I$(srctree)/drivers/input/touchscreen/lge_oos
subdir-ccflags-$(CONFIG_LGE_TOUCH_CORE_POS) += -I$(srctree)/drivers/input/touchscreen/lge_pos

obj-$(CONFIG_LGE_SET_LCD_BIAS) := lcd_bias.o

