#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI7807G)	+= touch_ili7807g.o
obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI7807G)	+= touch_ili7807g_fw.o
obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI7807G)	+= touch_ili7807g_mp.o
obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI7807G)	+= touch_ili7807g_apk.o
