#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI9881X)	+= touch_ili9881x.o
obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI9881X)	+= touch_ili9881x_fw.o
obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI9881X)	+= touch_ili9881x_mp.o
obj-$(CONFIG_LGE_TOUCH_ILITEK_ILI9881X)	+= touch_ili9881x_apk.o
